### ISSUE TITLE
currently have two errors...

### ISSUE THREAD

**Issue by micampbell** [iXab3r/Blazor.Rete.js#1]
Say, I just found your project because I was also interested in combining Blazor and Rete. In your current commit there are two errors. One I can fix and one I cannot.

line 110 of Index.razor under BlazorReteJs.Playground\Pages, we need to change
from
`Extra = new NodeParams`
to 
`ExtraParams = new NodeParams`
the second error, I cannot fix: line 163 of same file, I get the error: 
```
'BlazorReteEditor<NodeParams>' does not contain a definition for 'WhenTemplateCreated' and no accessible extension method 'WhenTemplateCreated' accepting a first argument of type 'BlazorReteEditor<NodeParams>' could be found (are you missing a using directive or an assembly reference?)
```

Are you able to fix these?

**Comment by iXab3r** [comment]
Hey, Matt,
Fixed both. 
Please keep in mind that Playground is extremely ugly and rough on edges as I've used it only at the very beginning of development. This library is used in my other project and most of the testing/integration is happening there. 

Foreseeing question about NuGet - probably will happen in April

If you're interested how it may look like when used in a project here is an example - this is an automation application which uses behaviour trees
![](https://i.imgur.com/FtUWMPd.png)
![](https://i.imgur.com/oitAqv1.gif)
https://wiki.eyeauras.net/en/behavior-trees/gettings-started
